# Generated by Django 3.2.5 on 2021-07-19 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_migrate_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
